name: Benchmark test

on: [push, pull_request]

jobs:
  common:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: 14.x

    - name: Install dependencies
      run: npm ci

    - name: Worker info
      run: |
        cat /proc/cpuinfo
        cat /proc/meminfo

    - name: Execute benchmark
      run: npm run bench common
      env:
        CI: true
